### ISSUE TITLE
Scaling Problem when entering Quantity

### ISSUE THREAD

**Issue by mrcheema** [KenKundert/quantiphy#14]
Hello, this my first issue report ever, so sorry if make some mistakes. I think when initializing the quantity there is something unclear or not correct. e.g.
```Python
>>> stress = Quantity('138 MPa')
>>> stress
Quantity('138 MPa')
>>> stress.as_tuple()
(138000000.0, 'Pa')
>>> stress = Quantity('138e6 Pa')
>>> stress
Quantity('138 MPa')
>>> stress.as_tuple()
(138000000.0, 'Pa')
>>> stress = Quantity('138 Pa')
>>> stress
Quantity('138e15 a')
>>> stress.as_tuple()
(1.38e+17, 'a')
```

The last value is not correct. Please see if it is a bug or I am not using it right. How can I enter stress in pascals ('Pa')?

Thanks,

**Comment by KenKundert** [comment]
The issue is that P is a valid scale factor, so QuantiPhy is taking Pa to be a peta-a (scale factor is peta and units are a).  I recommend that you read [Ambiguity of Scale Factors and Units](https://quantiphy.readthedocs.io/en/stable/user.html#ambiguity-of-scale-factors-and-units). You can solve this using a number of different approaches. Choose the one that works best in your situation:
```
>>> from quantiphy import Quantity

>>> print(Quantity('138 Pa'))
138e15 a
 
>>> print(Quantity('138 Pa', ignore_sf=True))
138 Pa

>>> with Quantity.prefs(input_sf='TGMkmunpfa'):
...     print(Quantity('138 Pa'))
138 Pa

>>> with Quantity.prefs(known_units='Pa'):
...     print(Quantity('138 Pa'))
138 Pa
```

**Comment by mrcheema** [comment]
Thanks, I will read the guide to properly use it in the right way. Thanks for you help is it is a great job. Really appreciate it.
