### ISSUE TITLE
Question on use

### ISSUE THREAD

**Issue by jeffwright13** [KenKundert/quantiphy#24]
Hello, 

Opening an issue here since the discussions aren't enabled on this repo.

I would like to use the `Quantity` object to handle a variable that represents milliseconds. I want to keep the number in ms units, since I am writing test code that passed on the value to some underlying Java that expects units of ms. Currently, quaniphy is showing me "kilo-milli-seconds", instead of the preferable "seconds. "

```
>>> t1 = Quantity(2500, "ms")
>>> print(t1)
2.5 kms
```

What I'd like to know is if I can tell quantiphy to normalize those units when printing, but still keep the internal number represented as milliseconds. I consulted the docs but didn't immediately see how to handle this situation.

**Comment by KenKundert** [comment]
The basic strategy with QuantiPhy is always to convert quantities to their base units and scale on the way in or out as needed.  That can simplify the process of writing code involving quantities because it eliminates the need to track which scale factors are used for all the quantities you use.  For example, you need not remember that one time value is given in ms and another in μs.  It is always s.

There are three basic tasks when unit quantities: converting values to quantities, using the value of quantities, and converting values from quantities.

So, assume that
1. you are given a value in ms that does not have the units attached,
2. you want use the value in a formula that assumes values in ms.
3. you want to output the with the units and the proper scale factor.

Then if you save the value as seconds, as is traditional with QuantiPhy, you would do the following:

```
>>> from quantiphy import Quantity

>>> given_value_by_user = 0.1
>>> period = Quantity(given_value_by_user, 's', scale=0.001)
>>> period_in_ms = 1000*period
>>> print(f"period in ms: {period_in_ms}\nperiod: {period}")
period in ms: 0.1
period: 100 us

```

If instead, you really want to keep the units in ms, you can do the following:
```
>>> given_value_by_user = 0.1
>>> period = Quantity(given_value_by_user, 'ms')
>>> period_in_ms = float(period)
>>> print(f"period in ms: {period_in_ms}\nperiod: {period.scale((0.001, 's'))}")
period in ms: 0.1
period: 100 us

```

If you want to allow the user to specify the value in a string, and allow them to give units if they wish, otherwise assume ms, then you can do the following

```
>>> from quantiphy import Quantity, UnitConversion

>>> s_to_ms = UnitConversion('s', 'ms', 0.001)
>>> print(s_to_ms)
s ← 0.001*ms

>>> given_value_by_user = '100 us'
>>> period = Quantity(given_value_by_user, scale='ms')
>>> period_in_ms = float(period)
>>> print(f"period in ms: {period_in_ms}\nperiod: {period.scale((0.001, 's'))}")
period in ms: 0.1
period: 100 us

>>> given_value_by_user = '0.1'
>>> period = Quantity(given_value_by_user, 'ms', scale='ms')
>>> period_in_ms = float(period)
>>> print(f"period in ms: {period_in_ms}\nperiod: {period.scale((0.001, 's'))}")
period in ms: 0.1
period: 100 us

```
In each of these cases you are following the same basic playbook: convert to the internal units when creating the quantity, and convert from the internal units when using the value. In the first example the internal units are seconds, and the other examples the internal units are milliseconds. 

When you are holding the value internally in milliseconds you never want to convert the value directly to a string unless you suppress the use of scale factors by setting _output_sf_=False or you use a format that does not output scale factors, such as _fixed_.  Otherwise you could end up with 1 kms.  Instead, you create another quantity, this time in terms of seconds, and you print its value.

**Comment by KenKundert** [comment]
Thanks for pointing out the discussions feature.  I was unaware of it.

**Comment by jeffwright13** [comment]
Thanks for the detailed explanation! I'll take this info and digest it.
